services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    volumes:
      - ./data/mongo:/data/db

    network_mode: host
  api:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.api.debug
    volumes:
      - ./haus_api:/app/haus_api
      - ./haus_api/haus_utils:/app/haus_api/haus_utils
      - ./plugins:/app/haus_api/plugins

    ports:
      - 8000:8000

    stop_signal: SIGINT
    depends_on:
      - mongo
    
    network_mode: host

  client:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.client.debug
    volumes:
      - ./haus_client:/app

    ports:
      - 5173:5173

    depends_on:
      - api
    
    network_mode: host