server:
  database:
    uri: mongodb://127.0.0.1:27017/
    database: haus
  
  security:
    sessions:
      expiration: 259200
    
    access_levels:
      internal:
        - 127.0.0.1
      
      privileged:
        - 192.168.0.0/24
      
      external:
        - "*"
